### ISSUE TITLE
setInputValue on checkboxes that have initial value false to true doesn't work.

### ISSUE THREAD

**Issue by imp-dance** [brainfoolong/form-data-json#3]
**Describe the bug**
**`FormDataJson.setInputValue()`** seems to work like this in the case of checkboxes:

`inputElement.checked = value === inputElement.value`

So, if the initial value is *false*, then `true === false` would return `false`.

**Expected behaviour**

`FormDataJson.setInputValue(input, true);` should set the input value to `true`.

**Actual behaviour**

`FormDataJson.setInputValue(input, true);` sets the input value to `false`.

**To Reproduce**
https://codepen.io/schart/pen/gOaYOGQ

**Proposed fix**

Changing [line 57](https://github.com/brainfoolong/form-data-json/blob/master/src/form-data-json.js#L57) from

`inputElement.checked = value === inputElement.value`

to

`inputElement.checked = value`

-----------------------------------

Is this here on purpose, or is it a bug?

**Comment by brainfoolong** [comment]
Thank you for your pull request. I came across this specific case in my tests and the current behaviour is exactly that what i wanted. It should only set the checkbox to true when the actual value is the same as the provided one. 

The reason is simple: The data what you can get from .formToJson should set exactly the same with .fillFormFromJsonValues. 

Imagine when you swap checkboxes in dom and they have no specific array key like `name=ids[]` than you definitely not want to set to true when the value doesnt match.

**Comment by brainfoolong** [comment]
Maybe special value like boolean true/false could work as check/uncheck in this case but i'm not sure to add different behaviour depending on the value.

**Comment by brainfoolong** [comment]
Nice catch. Thank you, i should add checkboxes to the demo as well.  In the real TestSuite at https://brainfoolong.github.io/form-data-json/tests/test.html there are all possible inputs.
